### ISSUE TITLE
`setWebhook` with `certificate` broken

### ISSUE THREAD

**Issue by d-w-x** [vendelieu/telegram-bot#32]
**Describe the bug**

The following code can't work as expected.

```kotlin
setWebhook("https://site.com/bots").options {
  certificate = ResourceUtils.getFile("classpath:site.com.pem")
}.send(bot)
```

[Telegram](https://core.telegram.org/bots/api#setwebhook) need [inputfile](https://core.telegram.org/bots/api#inputfile) but we provided the local path of the file.

**To Reproduce**

```kotlin
setWebhook("https://site.com/bots").options {
  certificate = ResourceUtils.getFile("classpath:site.com.pem")
}.send(bot)
```

https://api.telegram.org/bot[TOKEN]/getwebhookinfo: `"has_custom_certificate":false,` is always `false`.

**Comment by vendelieu** [comment]
Thanks for your report,
in general there is a difficulty with tg api in file issues because dynamically you have to change the request format to multipart if there is a file instead of an id or etc.

In other parts usually the method has been remodeled to custom processing, but I think the problem is overdue and needs to be solved more gracefully somehow.

I'll try to update the structure today and solve it.
I hope it won't prevent you from using the library and I'll be glad to get any feedback!

**Comment by vendelieu** [comment]
Can you try again with 3.0.3 release please :)
After reworking the multipart logic should now work correctly.

**Comment by d-w-x** [comment]
Thanks for your quick actions!

When using this library, I have another suggestion, which is about API parameters, let's take `declineChatJoinRequest` for example.

The function definition is `fun declineChatJoinRequest(userId: String) = DeclineChatJoinRequestAction(userId)`. Maybe `userId: String` is not a good idea.
Official doc is [here](https://core.telegram.org/bots/api#declinechatjoinrequest), and there maybe 3 problems (or other called? I can't think out a better noun):
1. Official doc is `Integer`. This is a difference.
2. This may confuse user whether they should pass the username (@something) or the user id.
3. Maybe we provide `fun declineChatJoinRequest(user: User) = DeclineChatJoinRequestAction(userId)` and parse userID in library could be better? If we want to provide more chose, we could also provide `fun declineChatJoinRequest(userId: Long) = DeclineChatJoinRequestAction (userId)`

I have found this in `declineChatJoinRequest` and `approveChatJoinRequest` methods. If this does matter, maybe we should check the whole project to make an improvement.

If you prefer, I can close this issue and copy this to a new one. After all, the problem associated with this issue has been resolved. Thanks for your work again.

Last, I'm not so familiar with English (In fact, it has been almost two years since I have written formal English content. (T⌓T)). I try my best to express a friendly and suggestive sentiment above, instead of **asking** for a breaking change. The final decision is yours.
Please understand if there is any offense in the above text.

**Comment by vendelieu** [comment]
Hey!
I'm more than happy to hear your suggestions on the api and it would be awesome if you suggest any improvements, feel free :)

about already suggested improvements, you are right, we should change it to Integer and it is also convenient to have an overload method using User.

If it is not difficult it would be better to transfer to a separate ticket, so that if anything the information is not lost :)
