### ISSUE TITLE
[feat request] Add http proxy and socks proxy to Telegram server

### ISSUE THREAD

**Issue by ShellWen** [vendelieu/telegram-bot#41]
I would like to add an API for setting network proxies, which is important in some cases. Please consider this. Thank you.

**Comment by ShellWen** [comment]
I see it in e78f82d. Thank you for your contributions to the Kotlin community! 🍻

**Comment by vendelieu** [comment]
Yes, maven publishing didn't go through due to errors with their server so it took a bit longer, but the new version should now be resolving.

If you want to use socka proxy try to exclude the cio engine and implement for example okhttp and it should work too.
Or take a look there:
https://ktor.io/docs/proxy.html#supported_engines
